baseURL: 'http://localhost:1313'
defaultContentLanguage: en
hasCJKLanguage: false
languageCode: en-us
paginate: 10
theme: mini
title: Dust In The City
enableRobotsTXT: true

taxonomies:
  category: categories
  geo: geo
  tag: tags

permalinks:
  posts: /posts/:year/:month/:slug/

markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

params:
  author: Dustin Michels
  avatarLink: 'http://localhost:1313/'
  bio: "Dustin's dispatches on urban planning: thoughts, observations, projects, and learnings."
  copyright: ''
  description: 'Dispatches on urban planning, emanating from Somerville.'
  enableComments: false
  enableGoogleAnalytics: false
  customCSS:
    - css/custom.css
    - css/modal.css
  customJS:
    - js/modal.js
    - js/table.js
  hiddenPostSummaryInHomePage: false
  math: false
  showPowerBy: false
  # Social links in footer, support github,twitter,stackoverflow,facebook
  social:
    github: https://github.com/dustinmichels/
    twitter: https://x.com/Dustin_Michels
  # showToc: true

# ignore Obsidian template
module:
  mounts:
    - excludeFiles: posts/_templates/*
      source: content
      target: content
    - source: 'node_modules/@fontsource-variable/open-sans'
      target: 'static/fonts/fontsource-variable/open-sans'
