baseURL: "http://localhost:1313"
defaultContentLanguage: en
hasCJKLanguage: false
languageCode: en-us
paginate: 30
theme: mini
title: Dust In The City

taxonomies:
  category: categories
  geo: geo
  tag: tags

markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

params:
  author: Dustin Michels
  avatarLink: "http://localhost:1313/"
  bio: "Dustin's dispatches on urban planning: thoughts, observations, projects, and learnings."
  copyright: ""
  description: "Dispatches on urban planning, emanating from Somerville."
  enableComments: true
  customCSS:
    - css/custom.css
  hiddenPostSummaryInHomePage: false
  math: false
  showPowerBy: false
  showToc: true

# ignore templates
module:
  mounts:
    - excludeFiles: _templates/*
      source: content/posts
      target: content/posts
