baseURL: 'http://localhost:1313'
defaultContentLanguage: en
hasCJKLanguage: false
languageCode: en-us
paginate: 3
theme: mini
title: Dust In The City

taxonomies:
  category: categories
  geo: geo
  tag: tags

permalinks:
  posts: /posts/:year/:month/:slug/

markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

params:
  author: Dustin Michels
  avatarLink: 'http://localhost:1313/'
  bio: "Dustin's dispatches on urban planning: thoughts, observations, projects, and learnings."
  copyright: ''
  description: 'Dispatches on urban planning, emanating from Somerville.'
  enableComments: true
  customCSS:
    - css/custom.css
    - css/modal.css
  customJS:
    - js/modal.js
  hiddenPostSummaryInHomePage: false
  math: false
  showPowerBy: false
  showToc: false

  # links:
  #   - name: Geo
  #     path: /geo

# ignore templates
module:
  mounts:
    - excludeFiles: posts/_templates/*
      source: content
      target: content
