baseURL: http://localhost:1313
languageCode: en-us
title: Dust In The City
theme: mini

# Default content language, support en (English) / zh (Chinese) / nl (Dutch) / fr (French) / es (Spanish) / da (Danish), default 'en'
defaultContentLanguage: en

hasCJKLanguage: false
# permalinks:
#   posts: /posts/:title/

paginate: 30

# googleAnalytics: your-google-analytics-id
# disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  github: your-github-link
  twitter: your-twitter-link
  stackoverflow: your-stackoverflow-link
  # facebook: your-facebook-link

# Site parameters
params:
  author: Dustin Michels
  bio: "Dustin's dispatches on urban planning: thoughts, observations, projects, and learnings."
  description: "Dustin's dispatches on urban planning: thoughts, observations, projects, and learnings."

  enableRSS: true
  enableComments: true
  enableGoogleAnalytics: true
  showToc: true
  showPowerBy: true
  math: false
  hiddenPostSummaryInHomePage: false
  copyright: ""

  # Extra links in navigation
  links:
    ## e.g.
    # - name: Project
    #   path: /project

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
    - css/custom.css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js

module:
  mounts:
    - excludeFiles: _templates/*
      source: content/posts
      target: content/posts
