# baseURL = "https://dustinthe.city/"
baseURL = "http://localhost:1313"

defaultContentLanguage = "en"
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
hasCJKLanguage = false
languageCode = "en-us"
paginate = 30
theme = "mini"
# theme = "paperesque"

title = "Dust In The City"

# [permalinks]
# posts = "/posts/:title/"

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#

[taxonomies]
category = "categories"
geo = "geo"
tag = "tags"

[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

# Social links in footer, support github,twitter,stackoverflow,facebook

# [social]
# github = "https://github.com/dustinmichels"
# stackoverflow = "your-stackoverflow-link"
# twitter = "your-twitter-link"

# Site parameters

[params]
author = "Dustin Michels" 
avatarLink = "http://localhost:1313/" 
bio = "Dustin's dispatches on urban planning: thoughts, observations, projects, and learnings." 
copyright = "" 
description = "Dispatches on urban planning, emanating from Somerville." 
enableComments = true # To enable comments, you may need to set `disqusShortname`
# enableGoogleAnalytics = true # To enable, you may need to set `googleAnalytics`
# enableRSS = true # To enable RSS, you could set `enableRSS: true`, default is `true`
customCSS = ["css/custom.css"] 
hiddenPostSummaryInHomePage = false # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
math = false # To enable math typesetting , you could set `math: true`, default is `false`
showPowerBy = false # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
showToc = true # To enable table of content, you could set `showToc: true`, default is `false`

[[module.mounts]]
excludeFiles = "_templates/*"
source = "content/posts"
target = "content/posts"

# [imaging]
# anchor = "Smart"
# bgColor = "#ffffff"
# hint = "photo"
# quality = 75
# resampleFilter = "Box"
